services:
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - ./prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run

volumes:
  grafana-storage:
