- name: Naikkan stack pemantauan
  hosts: mon
  become: true
  vars:
    docker_users: [ubuntu]
  roles:
    - geerlingguy.docker

  tasks:
    - name: Cipta folder stack
      file:
        path: /opt/monitoring
        state: directory

    - name: Hantar prometheus.yaml
      copy:
        src: prometheus.yml
        dest: /opt/monitoring/prometheus.yml

    - name: Hantar compose.yaml
      copy:
        src: compose.yaml
        dest: /opt/monitoring/compose.yaml

    - name: Get SSM parameter using the target node's AWS CLI context
      ansible.builtin.command: >
        aws ssm get-parameter 
        --name "/devops-bootcamp-2026/tunnel-token" 
        --with-decryption 
        --region "{{ ansible_aws_ssm_region }}" 
        --query "Parameter.Value" 
        --output text
      delegate_to: localhost
      register: ssm_result
      changed_when: false
      no_log: true

    - name: Save token to a fact for downstream tasks
      ansible.builtin.set_fact:
        cloudflare_api_token: "{{ ssm_result.stdout }}"
      no_log: true

    - name: Manage Docker Compose Stack (Equivalent to docker compose up -d)
      community.docker.docker_compose_v2:
        project_src: /opt/monitoring
        state: present
        pull: always               # Optional: Ensures you always have latest images
      environment:
        TUNNEL_TOKEN: "{{ cloudflare_api_token }}"