- name: Install Ansible on Controller node
  hosts: ctr
  become: true
  gather_facts: true
  vars: 
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name : Bootstrap required package bindings
      ansible.builtin.raw: apt-get update && apt-get install -y python3-apt python3-pip
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"
  
  tasks:
    - name: Ensure prerequisites are installed (Ubuntu/Debian)
      ansible.builtin.apt:
        name: 
          - software-properties-common
          - unzip
        state: present
        update_cache: false
      when: ansible_facts['os_family'] == "Debian"
    
    - name: Add official Ansible PPA repository (Ubuntu/Debian)
      ansible.builtin.deb822_repository:
        name: ansible-official
        types: deb
        uris: https://launchpadcontent.net
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: main
        state: present
      register: ppa_added
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"

    - name: Update apt cache if repository was ppa_added
      ansible.builtin.apt:
        update_cache: true
      when: ppa_added.changed

    - name: Install Ansible (Ubuntu/Debian)
      ansible.builtin.apt:
        name: ansible
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install required Python AWS SDK components
      ansible.builtin.apt:
        name:
          - python3-boto3
          - python3-botocore
        state: present
    # --- START OFFICIAL AWS CLI V2 INSTALLATION BLOCK ---
    - name: Check if AWS CLI v2 is already installed
      ansible.builtin.command: aws --version
      register: aws_cli_check
      failed_when: false
      changed_when: false

    - name: Download and install AWS CLI v2 bundle
      block:
        - name: Download AWS CLI zip installer
          ansible.builtin.get_url:
            url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: /tmp/awscliv2.zip
            mode: '0644'

        - name: Unarchive AWS CLI bundle
          ansible.builtin.unarchive:
            src: /tmp/awscliv2.zip
            dest: /tmp
            remote_src: true

        - name: Run AWS CLI installation script
          ansible.builtin.command: /tmp/aws/install --update
          changed_when: true
      when: aws_cli_check.rc != 0  # Only runs if "aws" command isn't found
      
    - name: Install AWS Session Manager Plugin (Debian/Ubuntu)
      ansible.builtin.apt:
        deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
        state: present
      when: ansible_facts['os_family'] == "Debian"
    
    - name: Setup destination folder
      file:
        path: /opt/ansible
        state: directory

    - name: Copy configs
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/ansible/
        owner: root
        group: root
        mode: '0644'
      loop:
        - ansible.cfg
        - compose.yaml
        - inventory.ini
        - playbook-web-stack.yaml
        - playbook-mon-stack.yaml
        - prometheus.yml
        - grafana-provisioning

    - name: Install all Ansible roles and collections on the control node
      ansible.builtin.command: "ansible-galaxy {{ item.type }} install {{ item.name }}"
      loop:
        - { type: 'role',       name: 'geerlingguy.docker' }
        - { type: 'collection', name: 'amazon.aws' }
        - { type: 'collection', name: 'community.docker' }
        - { type: 'collection', name: 'prometheus.prometheus' }          
      become: false
      changed_when: false